
workflows:
  ios-workflow:
    name: Build iOS App
    max_build_duration: 60
    environment:
      vars:
        XCODE_PROJECT: "ClipboardSyncApp.xcodeproj"
        XCODE_SCHEME: "ClipboardSyncApp"
      xcode: latest
    scripts:
      - name: Install CocoaPods dependencies (if any)
        script: |
          pod install || echo "No podfile found, skipping..."
      - name: Build the app
        script: |
          xcodebuild -project "$XCODE_PROJECT" -scheme "$XCODE_SCHEME" -sdk iphoneos -configuration Release clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
    artifacts:
      - build/ios/Release/*.app
      - build/ios/Release/ipa/*.ipa
